channels:
  - conda-forge
  - pytorch
dependencies:
  - pytorch=1.13
  - pytorch-lightning=1.9
  - fairscale=0.4.13
  - einops=0.6
  - h5py=3.8
  - numpy=1.24
  - scipy=1.10
  - openmpi=4.1
  - mpi4py=3.1
  - tqdm=4.64
  - wandb
  - opt-einsum
  - torchvision
  - tensorly
  - zarr
  - pip:
      - tensorly-torch
      - git+https://github.com/NeuralOperator/neuraloperator@3edd7e8
